version: '3.8'
services:
  pos-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: pos-api:local
    ports:
      - "5000:80"
    volumes:
      - pos_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

volumes:
  pos_data:
    name: pos_data
